### ISSUE TITLE
I didnt can put my custom sound URL

### ISSUE THREAD

**Issue by SpelerBR** [gamersclub-booster/gamersclub-booster#114]
I copied the link  but its not work 
The link that im using is https://www.myinstants.com/instant/cala-boca-puta-30435/?utm_source=copy&utm_medium=share

**Comment by henriquelbsouza** [comment]
You need to copy the .mp3 Url on the download button
![image](https://user-images.githubusercontent.com/1070818/136114567-8a1495f0-9864-48bd-9c28-04cab37118f5.png)

**Comment by SpelerBR** [comment]
Oh thk its working now
