### ISSUE TITLE
Bug - Inatividade

### ISSUE THREAD

**Issue by pablo-padua** [gamersclub-booster/gamersclub-booster#116]
Bug - Quando o jogador perde pontos por inatividade, há uma diferença entre o counter da extensao e da real pontuação do jogador.

Segue print do ocorrido:
![image](https://user-images.githubusercontent.com/46659839/136853622-4760b472-e97c-4356-ab44-0ac27e888885.jpg)

**Comment by nilkesede** [comment]
Corrigido na versão v2.15.4.

**Comment by henriquelbsouza** [comment]
Acabei de testar numa conta inativa, parece correto.
Corrigido no PR #149 vlw @nilkesede
