### ISSUE TITLE
Bug no skill level

### ISSUE THREAD

**Issue by ricardobr001** [gamersclub-booster/gamersclub-booster#120]
Salve pessoal, beleza?
Encontramos um bug no acompanhamento do progresso do skill level que fica la no header
Quando o player está no lvl 21, a extensão está colocando que o progresso do level 21 para o infinito como `NaN undefined`

![image](https://user-images.githubusercontent.com/18339710/140518714-693c0775-9682-405e-acaf-2e3342b99456.png)

Conseguiriam fazer esse ajuste?

**Comment by jvdavim** [comment]
Eu até faria o ajuste. O problema é ter uma conta nv. 21 para testar... kkk

**Comment by bfnzzl** [comment]
![image](https://user-images.githubusercontent.com/98098073/150341237-43e864b3-26b9-4756-90c2-7fa8b5426eb3.png)
o bug ainda ta foda ..

**Comment by jvdavim** [comment]
Opa, @bfnzzl. Esse bug que vc printou é outro. Ele foi inserido na última versão da extensão. Eu mesmo que fiz e já corrigi, porém ainda não saiu nas lojas. Em breve vai lançar e corrigir o problema.

**Comment by henriquelbsouza** [comment]
@ricardobr001 pode confirmar se foi corrigido o problema com o lvl 21?

**Comment by ricardobr001** [comment]
Aparentemente foi resolvido sim :clap: 

Firefox
![image](https://user-images.githubusercontent.com/18339710/150799680-bd71b0de-a101-45ba-855e-12b828236c56.png)

Chrome
![image](https://user-images.githubusercontent.com/18339710/150799720-4921a267-7ff3-4474-b8df-be8f7540695e.png)

**Comment by henriquelbsouza** [comment]
Blz, vlw pelo feedback, vou fechar a issue :)
