### ISSUE TITLE
Translate actions in the pages

### ISSUE THREAD

**Issue by henriquelbsouza** [gamersclub-booster/gamersclub-booster#128]
The actions from the extension like: "Adicionar a lista de bloqueio" or "COMPLETAR PARTIDA" and 
"CRIAR LOBBY PRE CONFIGURADA" should be translated based on the user selection in the extension.

Today it is only portuguese.

**Comment by barbozafernando** [comment]
I'm working on it already.

**Comment by henriquelbsouza** [comment]
@allcontributors please add @barbozafernando for development and translation

**Comment by henriquelbsouza** [comment]
@allcontributors please add @barbozafernando for dev and translation

**Comment by henriquelbsouza** [comment]
@allcontributors please add @barbozafernando for dev

**Comment by henriquelbsouza** [comment]
@allcontributors please add @barbozafernando for code

**Comment by henriquelbsouza** [comment]
Fixed on next release.
