### ISSUE TITLE
Dimensão do menu da GC buga quando ativado a extensão

### ISSUE THREAD

**Issue by crashzk** [gamersclub-booster/gamersclub-booster#132]
Dimensão da opção de exibir pontos para upar ou cair rank buga o menu da GC, ele é jogado para baixo.

![image](https://user-images.githubusercontent.com/32937653/151434047-748c003c-7592-499f-82d5-1e66c173fdeb.png)

![image](https://user-images.githubusercontent.com/32937653/151434192-4b0f57a9-55af-4f24-8f94-315ecbe7f6b1.png)

**Navegador: Google Chrome**

**Comment by jvdavim** [comment]
Olá. Provavelmente você usa resolução maior que 1920x1080, certo? Então, eu testei tudo com resolução Full HD (1920x1080), e descer o menu foi proposital, pois em alguns monitores você não consegue visualizar a barra completa, pois os itens ficam sobrepostos. A melhor solução para isso seria descer o menu somente se houver sobreposição, mas é um pouco mais chato de implementar. Vou tentar pensar em outras soluções. Se tiver alguma sugestão, pode mandar que avaliamos a possibilidade de implementar. Obrigado por abrir a issue!

**Comment by crashzk** [comment]
@jvdavim primeiramente obrigado pela resposta. Sobre a resolução, uso exatamente 1920X1080 nela pelo que entendi deveria funcionar tudo certo?

![image](https://user-images.githubusercontent.com/32937653/151464632-d10e3286-3a46-4c1d-a60f-c97383398e2f.png)

Acredito que uma possível solução, seria diminuir um pouco a fonte sobre as informações para upar ou cair de level. Pelo menos para mim até que é meio grande, um numero a menos seria bom acredito

![image](https://user-images.githubusercontent.com/32937653/151464849-66344666-7b54-4f2d-ae08-4ad23435415a.png)

Enfim, sinceramente não sei qual seria a melhor sugestão neste caso, acredito que esteja meio limitado a plataforma GC em si.

**Comment by jvdavim** [comment]
Então, dá uma olhada no zoom do seu navegador. Pode ser que esteja em zoom out. Eu vi aqui que dando zoom out libera bastante espaço. Acho que uma boa solução talvez seja além de arrastar o menu para baixo, arrastar o que sobrou em cima para o canto da direita. Eu já diminuí a fonte dos número que aparecemna barra de level comparado a versão anterior, mas vou ver se dá para diminuir mias sem prejudicar a legibilidade. Caso queria conversar sobre isso, pode usar nosso canal do discord. Lá temos um chat mais interativo.

**Comment by crashzk** [comment]
Verifiquei o zoom do navegador, tudo normal também.

Estarei entrando no discord, se puder informar o link ficaria grato. Sugestão até de adicionar ele e outros meios de contato e informações no `README.MD`.

**Comment by henriquelbsouza** [comment]
![image](https://user-images.githubusercontent.com/1070818/151618456-8c600d5e-21cb-4921-a597-ea741a2a6144.png)
Tem os links na própria extensão

https://discord.com/invite/umx6bbuawh

**Comment by henriquelbsouza** [comment]
A GC provavelmente mudou alguns espaçamentos/tamanhos, precisa de fix

**Comment by crashzk** [comment]
Só para registro, agora bugou a barra que mostra para upar/cair na GC:

![image](https://user-images.githubusercontent.com/32937653/158690118-727b55f6-d43a-424f-a6cf-fae5c5d00584.png)

Seria outro monitor, mas mesma resolução:

![image](https://user-images.githubusercontent.com/32937653/158690036-93ad4219-7d96-4d3f-9da4-748945616014.png)

Versão da extensão:
![image](https://user-images.githubusercontent.com/32937653/158690295-c9fccc3f-9be5-4e2c-9fa2-372b74d29756.png)

Configuração que estou usando:
```
{
    "autoAceitarReady": true,
    "autoConcordarTermosRanked": true,
    "autoFixarMenuLobby": true,
    "blockList": [],
    "enviarLinkLobby": true,
    "enviarPartida": true,
    "lobbyPrivada": true,
    "mensagemLida": true,
    "mostrarLevelProgress": true,
    "somReady": "https://www.myinstants.com/media/sounds/esl-pro-league-season-11-north-america-mibr-vs-furia-mapa-iii-mirage-mp3cut.mp3",
    "statusWebhook": "OK",
    "volume": "30",
    "webhookLink": "REMOVIDO"
}
```

**Comment by henriquelbsouza** [comment]
Can  you guys test on v2.15.1? It is going to the stores right now :)

**Comment by henriquelbsouza** [comment]
Fixed/Corrigido #145
