### ISSUE TITLE
Extensão não funciona no Mozila Firefox

### ISSUE THREAD

**Issue by crashzk** [gamersclub-booster/gamersclub-booster#135]
Extensão instalado e configurada, opção webhook não funciona, não envia o link via discord automaticamente e nem mostra a imagem do discord no lobby da GC.

![image](https://user-images.githubusercontent.com/32937653/152589498-52d201c1-46e8-4c48-8c00-cce368028ed8.png)

Já desativei e ativei a extensão e nada.

**Navegador Mozila Firefox**.

**Comment by henriquelbsouza** [comment]
Pode compartilhar a tela de configuração das integrações na extensão?

**Comment by crashzk** [comment]
> Pode compartilhar a tela de configuração das integrações na extensão?

![image](https://user-images.githubusercontent.com/32937653/153870476-2469daac-aeab-4b3d-a228-b33ac7d8e61c.png)

Mesma coisa que uso no Google Chrome no caso, nele funciona tudo certo. Testei até a opção de salvar a configuração e testar, ele envia no canal de discord a mensagem que esta tudo certo, porém quando cria a lobby não envia a mensagem e nem mostra o botão do discord no lobby.

**Comment by henriquelbsouza** [comment]
Valeu, vou ver se alguém pode dar uma olhada, ou tentar simular eu mesmo

**Comment by henriquelbsouza** [comment]
Seguinte @crashzk o discord está corrigido no CHROME. Pro firefox eu não consegui resolver. Acho que o próprio firefox tem bloqueio e não faz a request pra API do webhook do discord. Ainda não encontrei uma solução, farei isso quando tiver tempo, sugiro usar chrome, opera ou edge por enquanto.

**Comment by henriquelbsouza** [comment]
Vou fechar a issue como resolvida já que não teve resposta. Nos meus testes está tudo funcionando.
