### ISSUE TITLE
GC menu not visible when extension is active

### ISSUE THREAD

**Issue by paulostrix** [gamersclub-booster/gamersclub-booster#144]
![image](https://user-images.githubusercontent.com/55457217/159177271-7ebb7d31-4440-49b2-a083-7db9798cfc29.png)

Browser: Microsoft Edge
Resolution: 1920x1080

**Comment by Ckk3** [comment]
i'm having the same issue here

**Comment by crashzk** [comment]
Same thing here.

- **Browser:** Google Chrome
- **Resolution:** 1920x1080

![image](https://user-images.githubusercontent.com/32937653/159331766-0aba098b-eafa-4abe-806d-1b5e98e6b2dd.png)

I believe it may be related to the issues https://github.com/gamersclub-booster/gamersclub-booster/issues/132

**Comment by henriquelbsouza** [comment]
Can  you guys test on v2.15.1? It is going to the stores right now :)

**Comment by Ckk3** [comment]
Its all working now! Thank you so much for all effort you put on this extension <3
The "auto pick daily rewards" option was a such great idea. I hope u the best .

**Comment by henriquelbsouza** [comment]
The daily rewards was made by @leandroribeir0, thank him :P

Nem sei pq a gente fala inglês nas issues, mas suave hueuhehue
