### ISSUE TITLE
BUG com a função de coletar automaticamente o Daily Rewards

### ISSUE THREAD

**Issue by crashzk** [gamersclub-booster/gamersclub-booster#150]
Acredito que esteja tendo um bug com esta função. Tem dias que entro na plataforma GamersClub para coletar automaticamente o Daily Rewards e ele não faz isso, tenho que entrar na aba do Daily Rewards e coletar manualmente.

Isso ocorre ocasionalmente, pelo que vi não tenho como fazer para reproduzir este bug. Tem dias que entro faz tudo automático, só de entrar na plataforma ele já coleta automaticamente, tem outros dias que não.

Não sei se mais alguém esta enfrentando este problema, comigo ocorreu 3 vezes já.

**Navegador:** Google Chrome _(Versão 100.0.4896.60 - Versão oficial 64 bits)_

**Comment by leandroribeir0** [comment]
É isso mesmo, ele refaz a coleta se já se passaram 24h desde a última.

Quando eu desenvolvi a função eu não tinha percebido que é possível fazer a coleta a partir das 05h todos os dias, achei que tinha que aguardar 24h para fazer novamente.

Semana passada eu fiquei enrolado com o trabalho, mas essa semana eu já ajusto isso para a gente.

**Comment by leandroribeir0** [comment]
já fiz a alteração aqui @crashzk 

vou testar por uns dois dias e se estiver ok faço o pull request para o Henrique atualizar pra gente

**Comment by fillipe-ramos** [comment]
@leandroribeir0 Algum update?

**Comment by crashzk** [comment]
@leandroribeir0 não sei se seria possível, porém atualmente quando é coletado Daily Rewards não recebemos nenhum aviso, só remove a marcação da GC do menu.

![image](https://user-images.githubusercontent.com/32937653/162578216-6661247a-920b-4440-974b-007afa0f778a.png)

Antigamente ele mostrava uma caixa Pop-up que mostrava que você ganhou silves, da GC mesmo, agora quando coleta automaticamente não mostra.

![image](https://user-images.githubusercontent.com/32937653/162578262-51d82eec-ed14-47a3-99f8-c36f8459038e.png)

Nesta imagem ele mostrou pois coletei manualmente, já que não passou 24 horas para coletar automaticamente, mas seu eu deixar para pegar automaticamente esta caixa não mostra.

Enfim, seria possível corrigir isso, ou seria uma limitação da plataforma mesmo?

**Comment by leandroribeir0** [comment]
Eu teria que dar uma olhada em como esse popup é chamado.

Algumas vezes ele é exibido com a extensão também e outras não, quando eu tiver um tempinho vou dar uma olhada para exibir ele manualmente.

**Comment by henriquelbsouza** [comment]
@leandroribeir0 conseguiu dar uma olhada nisso? Aqui também é intermitente, mas não é algo que me incomode.

**Comment by jorgebrunetto** [comment]
Caso ocorra novamente reabrimos mas por enquanto tudo normal
