### ISSUE TITLE
Bug - freeze na página de ready

### ISSUE THREAD

**Issue by pablo-padua** [gamersclub-booster/gamersclub-booster#157]
Pessoal, após a subida do último PR, a extensão está dando freeze na página de ready, mesmo após todos os players aceitarem a partida

**Comment by henriquelbsouza** [comment]
Estranho, desde dezembro ou antes que não é alterado a parte de aceitar ready... E na parte de lobby faz uns 2 meses acho...

Vou ficar de olho nos próximos jogos, ontem pra mim funcionou normalmente (Chrome na ultima versão).

Se puder ficar com o console de desenvolvedor aberto antes e durante o processo de ready e verificar se toca algum erro pra vc e puder colar ele aqui será de grande ajuda.

Pode informar também o navegador?

**Comment by pablo-padua** [comment]
@henriquelbsouza chrome (ultima versao) e edge no pc do meu amigo, rolando o mesmo bug.

Página congelada no Ready:
![Aba ready](https://user-images.githubusercontent.com/46659839/162052147-b58be4a0-2e74-43a9-8825-18d53bd52555.jpg)
![Aba ready](https://user-images.githubusercontent.com/46659839/162052154-b602102e-cfbf-4506-b831-acdf07f9bff8.jpg)

**Comment by henriquelbsouza** [comment]
Pra mim não está acontecendo e é a mesma config que você, vou tentar resolver esse problema do trigger desnecessário pra ver se resolve.

**Comment by pablo-padua** [comment]
Cara, aparentemente resolveu sozinho... não faço ideia do que seja, ficou uns 2 dias assim, hoje joguei novamente e funcionou normalmente... talvez seja algo no browser ou na própria gc... obrigado pela atencao
