### ISSUE TITLE
Mostrar KDR na escolha de players da ranked

### ISSUE THREAD

**Issue by cabraljv** [gamersclub-booster/gamersclub-booster#161]
Adicionar KDR (e talvez winrate das ultimas 10 partidas) acima de cada player no menu de escolha de times na ranked

É possível de ser feito utilizando a API de history

`GET - https://gamersclub.com.br/api/box/history/{PLAYER_ID}`

Isso facilita muito a escolha de players nas rankeds, que na maioria das vezes é feita com base no lvl ou um completo tiro no escuro

Eu gostaria de implementar isso, o que acham?

**Comment by henriquelbsouza** [comment]
Vai fundo, só abrir um PR depois que a gente faz uma revisão/teste :)

**Comment by henriquelbsouza** [comment]
Se precisar de ajuda ou só trocar idéia, cola no nosso discord (tem na extensão em contato), eu to tentando ficar ativo la e o @jorgebrunetto ta dando uma moral também :D

**Comment by henriquelbsouza** [comment]
@cabraljv acho que não vai precisar kkkkk
![image](https://user-images.githubusercontent.com/1070818/171743000-d250428d-a63f-4ca1-84b3-b6702c59db37.png)

**Comment by henriquelbsouza** [comment]
Aparentemente só aparece depois que já escolheu (não tenho certeza, mas vou reabrir a issue)

**Comment by danielbeckera** [comment]
Esse KDR é relativo à ultima partida apenas, seria interessante ter a média do KDR, que foi o que o @cabraljv propôs.

**Comment by henriquelbsouza** [comment]
É, reabri =)

**Comment by nilkesede** [comment]
Fiz o PR #300 com uma solução funcional. Fiquem a vontade pra fazer sugestões.

**Comment by henriquelbsouza** [comment]
Resolvido pelo @nilkesede no pr #300, na versão v2.41.0 que já foi enviado pras lojas, só aguardar atualizar :)
