### ISSUE TITLE
Compatibilidade com o navegador Edge

### ISSUE THREAD

**Issue by danielbeckera** [gamersclub-booster/gamersclub-booster#182]
É muito complicado adicionar a extensão no EDGE?

**Comment by danielbeckera** [comment]
Nao tinha lido que tem como adicionar via chrome store.

**Comment by henriquelbsouza** [comment]
Tem um video aqui se ainda ficar com duvida: https://www.youtube.com/watch?v=rELLprJ15ug&feature=youtu.be&ab_channel=HenriqueS
