### ISSUE TITLE
Adicionar data de criação de conta e quantidade de partidas

### ISSUE THREAD

**Issue by jjunior89** [gamersclub-booster/gamersclub-booster#187]
Olá galera, será que é possível adicionar a quantidade de partidas que o player tem na GC e a data de criação da conta dele ? pois não ta importando muito o KDR, se a conta for antiga você sabe que a probabilidade de ser hacker é menor, vlw

**Comment by feliperugai** [comment]
Criei uma branch para trabalhar nisso.

branch: [feature-obter-dados-do-player](https://github.com/gamersclub-booster/gamersclub-booster/tree/feature-obter-dados-do-player).

Consegui fazer o código para obter todos estes dados que você comentou, está em [content-scripts/lobby/obterDadosDaConta.js](https://github.com/gamersclub-booster/gamersclub-booster/blob/feature-obter-dados-do-player/src/content-scripts/lobby/obterDadosDaConta.js).

Nos meus testes com esse código consegui todas as infos necessárias:

![image](https://user-images.githubusercontent.com/11398105/174393117-5e37ffeb-45a6-47e4-b0d4-e740ae241b02.png)


Porém estou sem tempo para jogar rs, e para adicionar estes dados na tela de lobby, preciso entrar numa lobby completa. Alguém consegue continuar a implementanção?

**Comment by SirCaveira** [comment]
Eu ia mesmo vir sugerir aqui esta ideia

Colocar a quantidade de partidas que os jogadores tem a mostra, como é com o KD. Assim como o win rate.

Colocar filtro por número de partidas, assim como tem pro KD também ajuda.

**Comment by SirCaveira** [comment]
Como faz pra instalar esse código que vc já criou ?

**Comment by jvdavim** [comment]
> Como faz pra instalar esse código que vc já criou ?

Olá, @SirCaveira. Segue a [documentação ](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/checking-out-pull-requests-locally#modifying-an-inactive-pull-request-locally)do github para o que vc quer fazer. Imagino, porém, que nesse caso o @feliperugai não chegou a criar um Pull Request. Isso torna mais fácil ainda. Basta criar sua própria branch e copiar e colar o código que ele linkou em [content-scripts/lobby/obterDadosDaConta.js](https://github.com/gamersclub-booster/gamersclub-booster/blob/187-adicionar-data-de-cria%C3%A7%C3%A3o-de-conta-e-quantidade-de-partidas/src/content-scripts/lobby/obterDadosDaConta.js). A partir daí é só dar continuidade na implementação.

**Comment by henriquelbsouza** [comment]
@feliperugai vi seu código ali, talvez seria mais interessante usar a própria API da GC: https://api.gamersclub.com.br/v1/user/id/17110
que já tem o create date, depois podemos mapear como pegar as partidas e ta, com certeza deve ter uma api pra isso...

O problema que eu vejo é a quantidade de requests que iria rolar. Já deixei de implementar outras features por esse motivo, imagina TODO mundo sendo "scaneado", 5 lobby é 25 request... imagina quando tiver 400 lobbies (limite premium), 2000 requests pra cada pessoa que tem a extensão instalada...

Temos que pensar em uma outra forma de fazer isso, isso ai poderia até mesmo derrubar o site da gamersclub...

**Comment by jjunior89** [comment]
> 

só com a data da criação de conta da GC já resolveria o problema e seria mais fácil também, o que tem de cara jogando xitado com conta de 1, 2 meses atrás, já evitaria

**Comment by henriquelbsouza** [comment]
> @feliperugai vi seu código ali, talvez seria mais interessante usar a própria API da GC: https://api.gamersclub.com.br/v1/user/id/17110 que já tem o create date, depois podemos mapear como pegar as partidas e ta, com certeza deve ter uma api pra isso...
> 
> O problema que eu vejo é a quantidade de requests que iria rolar. Já deixei de implementar outras features por esse motivo, imagina TODO mundo sendo "scaneado", 5 lobby é 25 request... imagina quando tiver 400 lobbies (limite premium), 2000 requests pra cada pessoa que tem a extensão instalada...
> 
> Temos que pensar em uma outra forma de fazer isso, isso ai poderia até mesmo derrubar o site da gamersclub...

Talvez pudéssemos adicionar apenas nos desafios? Pois em todas as lobbies acho impossível devido a quantidade de requests... =\

**Comment by henriquelbsouza** [comment]
Essa lupa no canto inferior direito, quando clica abre essa janela de estatísticas onde mostra o tempo de conta, partidas e % de vitória de cada player que está na lobby.

![image](https://user-images.githubusercontent.com/1070818/218091155-178e0460-e643-449c-accd-2fea996fe535.png)

Acredito que isso resolve essa issue. Vou deixar aberta por uns dias caso alguém queira comentar algo mais. @jjunior89 @SirCaveira
