### ISSUE TITLE
Sugestão de nova visualização de lobbies

### ISSUE THREAD

**Issue by thawankeane** [gamersclub-booster/gamersclub-booster#191]
# Overview
A tela de visualização de lobbies por se tratar de uma tela onde ocorre muitas atualizações (lobbies sumindo e aparecendo) acaba sendo um pouco problematica e gera uma visualização não muito limpa.

Essa issue tem o intuito de trazer uma discussão sobre o esforço e a UX de uma nova visualização dessa tela (também a viabilidade).

# Wireframes
Pensando de forma rápida, acredito que podemos pensar em uma visualzação um pouco mais simplificada como listas, mas o intuito é inicar uma discussão de UX do que seria melhor (talvez até mesmo se basear em outras plataformas ou jogos).

Basicamente o que temos hoje é isso:

<img src="https://user-images.githubusercontent.com/26743815/174662059-180d050a-db72-4380-b72a-24b905635154.png" width=70% height=70%>

O que me veio a cabeça foi algo assim:

<img src="https://user-images.githubusercontent.com/26743815/174662569-d4d95355-e122-43ee-ae3c-36d029e85c81.png" width=70% height=70%>

Na minha opinião essa visualização fica um pouco mais limpa, e em caso de atualização de lobbies sumindo ou aparecendo, a alteração visual de uma lista fica muito mais leve.

Isso apenas criaria um problema que seria onde ficariam as demais informações dos jogadores em que a GC deixa em evidência hoje, como a medalha e etc.

Lembrando que não sou UI/UX designer, se algum quiser colaborar e dar sugestões na issue, fique a vontade!

**Comment by jorgebrunetto** [comment]
Excelente, @henriquelbsouza .. Thawan é meu brother da cidade aqui, vou dar uma atenção nessa ideia que curti bastante tbm

**Comment by henriquelbsouza** [comment]
Eu só tomaria cuidado pra não tirar nada que é da própria GC, medalhas, plus/premium, etc...

**Comment by jorgebrunetto** [comment]
Com ctz... acho que podemos manter tudo e meio que deixar pro cara ativar ou não para seleção assim dentro da extensao

**Comment by thawankeane** [comment]
> Eu só tomaria cuidado pra não tirar nada que é da própria GC, medalhas, plus/premium, etc...

E se deixássemos as informações dos players em um pophover no hover? Quase que como é feito na tela de vetos?

**Comment by jorgebrunetto** [comment]
Feito a nova compacta, não deu exatamente como desenhou mas, agora já aparece varias em uma unica lista e tambem as infos com hover
