### ISSUE TITLE
Minhas Partidas

### ISSUE THREAD

**Issue by hezzycs** [gamersclub-booster/gamersclub-booster#194]
Se for possível quando clicar em minhas partidas ficar a mostra qnts pontos ganhou em cada partida sem precisar abrir a partida

**Comment by henriquelbsouza** [comment]
Parece interessante, vou pensar em uma forma de implementar isso.

**Comment by henriquelbsouza** [comment]
@hezzycs da uma olhada no pullrequest #203

**Comment by henriquelbsouza** [comment]
Ta na ultima versão!
