### ISSUE TITLE
Automatic collect daily rewards

### ISSUE THREAD

**Issue by MAN0CA07** [gamersclub-booster/gamersclub-booster#236]
Automatic collect daily rewards doesn't working for me. I've try to reinstall the extension, but still not working. Can u guys help me?

**Comment by EMathioni** [comment]
The GC daily reward system has changed, we're aware about this, but we'll see about this yet

**Comment by MAN0CA07** [comment]
Salve, Eduardo!!! Não sabia que era BR. Hahaha
Mas beleza, cara. Fico no aguardo. Muito obrigado!!!

**Comment by henriquelbsouza** [comment]
@MAN0CA07 corrigi na ultima versão, consegue testar ai? Aqui funcionou de boa...

**Comment by henriquelbsouza** [comment]
Aqui continua funcionando, como não obtive resposta, vou fechar a issue. Se quiser, pode abrir novamente a qualquer momento. Fix está na versão v2.34.5

**Comment by MAN0CA07** [comment]
Desculpe-me, Henrique. Não tinha visto tua msg, mas voltou a funcionar aqui sim. Muitíssimo obrigado, meu caro!
