### ISSUE TITLE
Opção de sair da lobby, enviar, colocar senha bugado

### ISSUE THREAD

**Issue by crashzk** [gamersclub-booster/gamersclub-booster#252]
Quando ativo a extensão o menu da GC buga a a sala do lobby que estou.

Menu GC sobrepoem as opção de sair da lobby, enviar e etc.

![image](https://user-images.githubusercontent.com/32937653/203993608-e23710f0-f6b6-4d67-ac2c-a1ff331e7641.png)

Desativando a extensão volta ao normal.

![image](https://user-images.githubusercontent.com/32937653/203994062-822c3989-1889-48dd-b86c-295c516ff8cc.png)

**Comment by henriquelbsouza** [comment]
![image](https://user-images.githubusercontent.com/1070818/203996994-25564feb-18f3-491d-83c5-ad874b33233f.png)
Pode desativar o fixar menu lobby pra ver se resolve? Essa nova barra acho que cagou o CSS, vou anotar pra arrumar isso.

**Comment by crashzk** [comment]
Resolveu desativando esta opção.

**Comment by crashzk** [comment]
Apenas um feedback, commit 428adc998c29ea4b81dfa88e247a14ec5e3a8752 ainda não resolveu o bug do fixar o lobby,

**Comment by henriquelbsouza** [comment]
Acho que por hora ta só do lado dos desafios, nesse lado ta como a gc trata, n ta sendo manipulado pela extensão

**Comment by henriquelbsouza** [comment]
Quando arrumarmos do lado esquerdo a gente fecha

**Comment by jorgebrunetto** [comment]
Eu já havia corrigido na ultima versão.
