### ISSUE TITLE
Adicionar os nomes do time na lobby

### ISSUE THREAD

**Issue by crashzk** [gamersclub-booster/gamersclub-booster#264]
Fazer que a extensão pegue o nome dos times e coloque em vez de **Time A** e **Time B.**

![image](https://user-images.githubusercontent.com/32937653/212107964-f1d612db-e8a0-499c-a60c-fc04478edac0.png)

Quando a lobby for criada mostrar o nome dos líders da sala como nome dos times, como a GC faz no nomes dos times no servidor. Se for um time/clan fechado mostrar o nome do time, igual GC mesmo.

**Comment by henriquelbsouza** [comment]
Resolvido pelo @dchueri no #272 !

Valeu!
