### ISSUE TITLE
ATIVEI A EXTENÇÃO

### ISSUE THREAD

**Issue by Soriu** [gamersclub-booster/gamersclub-booster#267]
Boa noite,

Instalei a extensão mas não esta ativando no site... não aceita automaticamente nem aparece o KDR nos lobbys

**Comment by jorgebrunetto** [comment]
é necessario clicar nela e ativar 
![image](https://user-images.githubusercontent.com/5823077/212546148-fc7f1c1a-3d0d-4b27-b108-d1dbf0dcb45c.png)

**Comment by Soriu** [comment]
ja ativei tudo mas não aceita o ready e nem aparece o KDR das pessoas no lobbys

**Comment by jorgebrunetto** [comment]
Verifica se ativando essas duas opções vai

![image](https://user-images.githubusercontent.com/5823077/212571046-cdab0c16-d079-4ef9-a446-d8147a19ea2d.png)
![image](https://user-images.githubusercontent.com/5823077/212571058-7eeecb5f-051a-47b0-97ee-4237b9b72be0.png)

**Comment by Gabrielpdev** [comment]
Tambem estou com esse mesmo problema, está tudo ativado, mas nao aparece nada no site, nao funciona nada. As configurações estao iguais no print, tanto na extensao quanto no navegador, estou utilizando Opera GX.

Versão do Opera:
`Sua versão é aLVL 4 (core: 94.0.4606.64)`

Versão do GamersClub Booster:
`GamersClub Booster
Versão 2.35.13`

**Comment by henriquelbsouza** [comment]
Obrigado pelo report @Gabrielpdev 

@Soriu pode tentar atualizar o navegador como fez o Gabriel pra ver se resolve?

**Comment by Soriu** [comment]
agora que atualizei deu certo... obrigado! estou na versão 
![image](https://user-images.githubusercontent.com/122707166/214151162-ab049410-cea1-4abd-9312-781234785717.png)

**Comment by henriquelbsouza** [comment]
Boa, obrigado pelo feedback, fechando a issue
