### ISSUE TITLE
BUG na opção de avaliar jogadores no fim da partida

### ISSUE THREAD

**Issue by crashzk** [gamersclub-booster/gamersclub-booster#268]
Notei que sempre que termino a partida e vou avaliar jogadores clico apenas em um jogador para avaliar e fecha o sistema de avaliação dizendo que a avaliação já foi enviada para todos jogadores.

No caso gostaria de avaliar todos jogadores, mas sempre só avalia um e depois finaliza/envia a avaliação.

Pensei que era da GC mesmo, porém desativei a extensão e fica tudo normal.

Não sei se teria etapas para reproduzir, eu particularmente só jogo um lobby fechada com amigos e sempre da isso.

Meu navegador seria Google Chrome.

**Comment by henriquelbsouza** [comment]
Vou investigar, não aconteceu comigo ainda.

**Comment by crashzk** [comment]
Apenas curiosidade, conseguiu reproduzir? Aqui ainda continua ocorrendo a toda partida, qualquer coisa gravo um vídeo para anexar aqui.

**Comment by henriquelbsouza** [comment]
@crashzk pode ver se resolveu?

**Comment by crashzk** [comment]
@henriquelbsouza problema continua aqui para mim, clico para votar em um player e depois fecha as opções de avaliar os outros jogadores..

**Comment by henriquelbsouza** [comment]
Qual versão da extensão? Aqui to conseguindo votar nos 9 players sem problemas.

Tem alguma coisa diferente pra esse jogo? É ranked/lobby? Drop de caixas? Ganhou/Perdeu?

**Comment by crashzk** [comment]
Versão da extensão: 2.35.14

![image](https://user-images.githubusercontent.com/32937653/215333369-d1ce7c4f-c275-401a-bff0-f07a11771da7.png)

Jogo lobby, time fechado sempre. Última partida que joguei e ocorreu bug, sem drops, ganhamos.

https://gamersclub.com.br/lobby/match/18423316

Vou notar também se acontece quando perdemos, não lembro.

Verificar também se ocorre quando eu deixo para avaliar a partida futuramente, não avaliar na hora que acaba o game.

**Comment by fanti1** [comment]
> Notei que sempre que termino a partida e vou avaliar jogadores clico apenas em um jogador para avaliar e fecha o sistema de avaliação dizendo que a avaliação já foi enviada para todos jogadores.
> 
> No caso gostaria de avaliar todos jogadores, mas sempre só avalia um e depois finaliza/envia a avaliação.
> 
> Pensei que era da GC mesmo, porém desativei a extensão e fica tudo normal.
> 
> Não sei se teria etapas para reproduzir, eu particularmente só jogo um lobby fechada com amigos e sempre da isso.
> 
> Meu navegador seria Google Chrome.

Afirmo que o mesmo acontece aqui, neste instante acabei de avaliar apenas um jogador e o submit do a avaliação inteira parece ter sido ativado automaticamente...

**Comment by crashzk** [comment]
Eu andei verificando a fundo esse bug. Notei que ocorre, pelo menos comigo, sempre quando avaliamos positivamente o jogador.

Ou seja, quando clicamos para avaliar o primeiro jogador positivamente fecha por completo sistema de avaliação, como se tivesse ido para todos. Porém se a primeira avaliação for negativa, consigo avaliar os outros jogadores normalmente, mesmo sendo as próximas avaliações positivas ou negativas.

**Comment by jorgebrunetto** [comment]
isso aconteceu cmg agora com a extensao desativada, é da GC.

**Comment by crashzk** [comment]
> isso aconteceu cmg agora com a extensao desativada, é da GC.

Estranho, já joguei vários jocom com a extensão desativada, nunca aconteceu, vou testar novamente para ver se acontece também.

**Comment by jvdavim** [comment]
Se puderem, capturem o log do console pelo devtools do navegador. Como é um comportamento programático, fica fácil de capturar, daí facilita para entender se é ou não da extensão.

**Comment by crashzk** [comment]
@jvdavim feito. Extensão ativa, versão mais recente dela.

[gamersclub.com.br-1675972131984.log](https://github.com/gamersclub-booster/gamersclub-booster/files/10700982/gamersclub.com.br-1675972131984.log)

![image](https://user-images.githubusercontent.com/32937653/217922126-c89b4921-e7ea-419a-8ebc-89615b32571e.png)

**Comment by henriquelbsouza** [comment]
Cara, nada é da extensão ai... Muito estranho... Acabei de testar aqui e ta normal, extensão ativa na última versão

https://user-images.githubusercontent.com/1070818/217943997-146812d8-24cd-4096-a372-ebcff10aa96d.mp4

**Comment by crashzk** [comment]
kkk

Vou desativar todos minhas extensão e jogar na GC e testar, depois testo só com a extensão GamersClub e vejo novamente, finalziando ativo todas extensões novamente e vejo.

Né possível, só comigo ficar bugando. kkk

**Comment by henriquelbsouza** [comment]
Eu acabei de ver que quando negativa/positiva um usuário a GC salva isso como feedback (aqueles quadradinhos novos pra criar anotações)

Eu acho que era um bug do lado deles com essa nova feature e que foi resolvido, pois isso não acontecia antes.

**Comment by crashzk** [comment]
@henriquelbsouza é, problema não é a extensão, mesmo com ela desativada o bug ocorreu.

Aparentemente GC mesmo, nenhum extensão esta ativa no meu navegador.

**Comment by henriquelbsouza** [comment]
Obrigado pelo retorno
