### ISSUE TITLE
Adicionar opção de jogar com na aba de lobby

### ISSUE THREAD

**Issue by crashzk** [gamersclub-booster/gamersclub-booster#279]
Ter opção de deixar pré-configurado a configuração da lobby de **jogar com** quando formos criar um lobby.

![image](https://user-images.githubusercontent.com/32937653/217266817-6a802f95-cb42-480e-bb54-f423dd291a1a.png)

Assim quando nós criar a lobby já vem configurada também.

**Comment by henriquelbsouza** [comment]
Resolvido no PR #295

**Comment by henriquelbsouza** [comment]
Enviei pro chrome, daqui a pouco deve estar liberado v2.39.0
