### ISSUE TITLE
Implementação no site csgo.gamersclub.gg

### ISSUE THREAD

**Issue by davidhirle** [gamersclub-booster/gamersclub-booster#28]
Fala mano,
Excelente trampo!
Se possível, implementa no plugin o funcionamento no site csgo.gamersclub.gg também!
Parece que a gc vai mudar de domínio e colocar o nome jogo antes do gamersclub.gg dentro de alguns meses...
Abraço.

**Comment by henriquelbsouza** [comment]
Hoje já funciona esse domínio se não me engano, não quer contribuir e adicionar os endpoints corretos no manifest.json? Só abrir um PR :D

**Comment by henriquelbsouza** [comment]
@all-contributors please add @davidhirle for bug

**Comment by henriquelbsouza** [comment]
@all-contributors please add @davidhirle for bug

**Comment by henriquelbsouza** [comment]
Te adicionei como contribuidor, obrigado pelo Report :)

**Comment by henriquelbsouza** [comment]
Vou liberar a versão assim que fizer merge do outro PullRequest
