### ISSUE TITLE
check player

### ISSUE THREAD

**Issue by tibazera** [gamersclub-booster/gamersclub-booster#288]
ter um check de player que tem poucas horas na GC/CS GO

Pra evitar cair contra cheat / new player / smurf

**Comment by crashzk** [comment]
Não seria a opção de **jogar com** *(Status Prime, Verificado)* que a GC já tem?

![image](https://user-images.githubusercontent.com/32937653/217814475-3812eebc-8977-47f8-9199-e87940829752.png)

Questão de horas/smurf ai já tem não como evitar, acredito que nem seja o foco da extensão colocar este recurso.

**Comment by henriquelbsouza** [comment]
@tibazera @crashzk fizemos o release ontem de uma feature nova, acho que ficou legal. Se puderem testar e dar o feedback :)

**Comment by henriquelbsouza** [comment]
Essa lupa no canto inferior direito, quando clica abre essa janela de estatísticas onde mostra o tempo de conta, partidas e % de vitória de cada player que está na lobby.

![image](https://user-images.githubusercontent.com/1070818/218090932-2f6adcf9-74cb-4f2f-88fb-08b7c3dd6ab6.png)
