### ISSUE TITLE
janela em java para lobby

### ISSUE THREAD

**Issue by tibazera** [gamersclub-booster/gamersclub-booster#289]
pode soar bem noob
mas teria como criar uma janela em java só pra buscar as partidas e entrar na lobby sem necessidade de usar o browser?

estou começando no mundo da tecnologia mas ja vi varias pessoas fazendo isso em outros apps pra reduzir o consumo de memória que o browser traz.

**Comment by henriquelbsouza** [comment]
Eu comecei um projeto utilizando Tauri, não é em Java e sim em Rust.

O projeto está aqui: https://github.com/henriquelbsouza/gamersclub-desktop

Basicamente ele abre o site da GC e adiciona algumas features da extensão.

Não dei continuidade pois pra gerar o build, etc. teria um custo relativamente alto anual que eu não estou disposto a arcar.

Pra fazer algo mais "focado", sem ser direto utilizando o site da GC, teria que ser com a própria GC, uma vez que tem autenticação, apis que não conhecemos e websockets. Se fizer engenharia reversa talvez seja possível, mas demandaria muito tempo e não é o meu foco no momento.

**Comment by henriquelbsouza** [comment]
Me avisa se tiver algo mais a acrescentar.

Vou fechar a issue em breve
