### ISSUE TITLE
bug: abrir várias janelas seguidas de lobby info cria listas desordenadas

### ISSUE THREAD

**Issue by dudztroyer** [gamersclub-booster/gamersclub-booster#298]
### Como reproduzir:
1- Abra o lobby
2- Clique no novo botão de ver a lobby info de um lobby aleatório 
3- Feche o lobby info e abra novamente diversas vezes rapidamente
4- A lista cresce até completar todos os requests de acordo com quantas vezes foi fechado e aberto o lobby info.

### Problema no código:
https://github.com/gamersclub-booster/gamersclub-booster/blob/f674dc6718b6315c18b470cb678aa9de8c29cfbe/src/content-scripts/lobby/infoLobby.js#L20-L30

### Como resolver?
Primeiramente temos 3 coisas que podem ser melhoradas: 
1- o bug descrito
2- A ordem que vai aparecer é de acordo com a ordem dos requests
3- requests repetidos para o mesmo player sendo feitos quando se abre lobby's que ele está

Pra resolver essas três questões, eu sugiro fazer uso de um cache pra esses requests, de forma que se ele já existe, puxa do cache. Se não existe, faz o request e salva no cache. Dessa forma, evitamos usar um async na hora de inserir os dados no modal, evitando dados sendo inseridos fora de ordem. No ato do request, podemos definir o cache como "request pending", de forma que evite fazer o request 2x.

**Comment by henriquelbsouza** [comment]
Na última versão é possível clicar em apenas uma lobby por vez (a lupa some) e ai vc pode ir pro próximo, mas a anterior não fecha. Isso resolveu esse bug nas lobby central, mas não nas do desafio, assim que puder vejo com calma. Obrigado pelo report.
