### ISSUE TITLE
Sugestão: Customização do "Completar Partida"

### ISSUE THREAD

**Issue by SrMilton** [gamersclub-booster/gamersclub-booster#317]
Seria interessante ter uma forma de customizar o tipo de partida que você esta disposto a jogar com a função "Completar partida" ativada. Cansei de usar essa função para procurar partidas rapidas e ser colocado em uma partida 0x0, e pior, em um mapa que eu não gosto de jogar.

Então as novas features seriam:
Round minimo: Não aceitar partidas que estiverem menos de X rounds jogados (pra evitar aprtidas 0x0)
Diferença maxima entre placares: Não aceitar partidas que tiverem a diferença de placares maiores que X (evitar pegar partidas em que um dos times ja esta tomando um pau)
Vetar mapas: Poder escolher quais mapas você quer ou não quer que o Auto Complete aceite automaticamente.

**Comment by DanielHeringer** [comment]
Seria um sonho!!

**Comment by SrMilton** [comment]
@DanielHeringer tomei a liberdade de desenvolver essas funções eu mesmo. Ja estou avançado no desenvolvimento, falta terminar algumas coisas do backend que estou sem tempo nesse momento. Ja upei na minha fork a versão com todo o front feito, conforme eu for finalizando as funções eu ja vou dando push la e quando tiver tudo pronto eu abro o pr.

**Comment by bioneoficial** [comment]
@SrMilton tava dando uma olhada nessa extensao agora, voce esta finalizando essa Issue, precisa de algum colab no backend

**Comment by DanielHeringer** [comment]
@SrMilton Hoje tirei um tempo pra finalizar a feature, essa semana abro o PR...

**Comment by SrMilton** [comment]
@DanielHeringer Show, ficamos no aguardo então. Não tive tempo de jogar uma unica partida desde a minha ultima resposta aqui, infelizmente atolado de trabalho. Agradeço a ajuda.

**Comment by SrMilton** [comment]
@henriquelbsouza Quando lança a atualização atual na loja do Chrome?

**Comment by SrMilton** [comment]
@henriquelbsouza Eu não participei em nada do back. Hoje estou com dia livre, se quiser posso testar, gravar e publicar os testes para você. Caso exista bugs eu ja aponto aqui.

**Comment by henriquelbsouza** [comment]
Pode ser sim, vlw :)

**Comment by SrMilton** [comment]
Não esta funcionando, a função auto completar esta ignorando todos os filtros exatamente como era antes. 
@henriquelbsouza não sei se foi você que criou essa função inicialmente, mas pode confirmar se é essa parte do codigo que realiza a aceitação automatica do complete?
https://github.com/gamersclub-booster/gamersclub-booster/blob/development/src/content-scripts/lobby/botaoAutoComplete.js#LL83C1-L84C1

Lembrando que essas 2 linhas que estão em highlight são originais do seu codigo. Talvez os filtros estejam aplicados no lugar errado pois mesmo após eu comentar essas 2 linhas fora, a extensão AINDA esta aceitando partidas de complete.

**Comment by henriquelbsouza** [comment]
Não sei se entendi, tem como confirmar que só tem uma extensão rodando? Pode ser que esteja rodando a sua local de dev + a extensão da loja.

Se estiver assim, você precisa antes desativar a da loja pra poder testar, ou vai executar os dois códigos

**Comment by SrMilton** [comment]
Claro, só a extensão em debug esta ativa. Como eu disse, eu removi as linhas em highlight e mesmo assim a extensão ainda esta aceitando partida automaticamente, e sinceramente esta sendo bem dificil de fazer debug assim visto que eu faria utilizando print no console, mas estou tendo que jogar uma partida inteira a cada falha 🥴

![image](https://github.com/gamersclub-booster/gamersclub-booster/assets/35127424/b82a7761-b14d-43a1-8a48-a4a7f235fee0)

**Comment by henriquelbsouza** [comment]
Vc rodou "npm run dev" depois de fazer pull de development desse repo? As vezes o código ta desatualizado, mas deveria ser por ali mesmo

**Comment by SrMilton** [comment]
**Exatamente** isso, amigo. O codigo em sí esta todo atualizado, as minhas alterações são aplicadas em tempo real assim como foi em todo desenvolvimento do front, só que por algum motivo toda essa sessão de filtros é como se estivesse codada no lugar errado. Eu posso até gravar com detalhes logo após o almoço. Não posso correr o risco de ter que jogar uma partida inteira agora.

**Comment by henriquelbsouza** [comment]
Botei rodar o autocomplete aqui sem abrir o anticheat, to esperando aparecer uma partida pra ver o que acontece... Bem estranho estar aceitando auto...

Vamos ver, se descobrir algo te aviso

**Comment by henriquelbsouza** [comment]
Você pode testar sem abrir o anticheat/csgo, vai dar a mensagem de que precisa abrir o anticheat pra poder completar*

**Comment by henriquelbsouza** [comment]
Aqui não aceitou automático quando coloquei umas configs meio zoadas, só anubis de mapa 30round min e 1 de diferença...

Vou testar um por um agora pra ver... 

![image](https://github.com/gamersclub-booster/gamersclub-booster/assets/1070818/82b7b1bb-e53e-4efa-a9d9-2f0977ceef77)

**Comment by henriquelbsouza** [comment]
Cara, a principio aqui ta funcionando, coloquei max de diferença de rounds em 5, achou um de 7 diff e não aceitou, depois um que tava 3 e foi... O mesmo pra rounds minimos, com 30 n aceitou, mas com 5 aceitou... To testando o mapa agora

**Comment by henriquelbsouza** [comment]
É, pra mapas ta funcionando também, muito estranho essa parada que ta rolando com você... Desculpa se pareceu chato, queria só fazer um step-by-step e garantir que tudo estava atualizado e funcionando corretamente... De fato não sei o que dizer... Acho que uma coisa que percebi é que mudando as opções sem atualizar a página, fica com as configs antigas, mas imagino que você já testou isso também...

**Comment by henriquelbsouza** [comment]
Fiz o release pras lojas na versão 2.42.5.

Testei aqui e esta funcional, se alguém tiver problemas pode reabrir essa issue ou abrir uma nova.

Obrigado @SrMilton e @DanielHeringer pela contribuição <3

**Comment by SrMilton** [comment]
@henriquelbsouza Fala Henrique, sem problemas amigo, não tem situação chata entendo que estamos só querendo resolver. Debugando a versão oficial baixada diretamente da loja do chrome consegui descobrir que o **problema não esta nos filtros de round, e sim no de mapas**. Quando deixamos nenhum mapa marcado em vez de ele aceitar nenhum complete, ele aceita qualquer um que cabe no filtro dos rounds. 

https://github.com/gamersclub-booster/gamersclub-booster/assets/35127424/7c727dc6-f5fd-4362-9032-c82cbf4a019a

Felizmente é algo bem mais simples do que eu esperava, mas ainda é um problema. Pode testar por conta propria, se quiser que eu abra uma nova issue com esse bug, sem problemas.

**Comment by henriquelbsouza** [comment]
Mas acho que esse comportamento faz sentido né, uma vez que não vem nenhum selecionado por padrão

**Comment by SrMilton** [comment]
Bem, neste caso acredito que o correto seria deixar todos os checkbox marcados como default (não pensei nisso quando fiz). Valeu pela ajuda e que bom que conseguimos tirar essa feature do papel. Um abraço a todos que participaram e desculpe prolongar isso mais do que o necessario.

**Comment by henriquelbsouza** [comment]
Acho que da pra deixar assim, se eu pensar em algo melhor eu implemento... Mas nesse caso acho que ta legal, até pq n faz sentido NADA selecionado esperar que filtre, não iria completar nenhum jogo nunca...

Valeu pela ajuda, e quanto ao tempo, fica tranquilo é normal a gente faz quando sobra uns minutos mesmo =p

**Comment by DanielHeringer** [comment]
Boa noite pessoal, a ideia foi essa mesma, se não tem nada marcado aceita qualquer um... Que bom que resolveram, obrigado pela ajuda
