### ISSUE TITLE
Requisições descessárias para serviços da Gamers Club

### ISSUE THREAD

**Issue by DanillodeSouza** [gamersclub-booster/gamersclub-booster#318]
Na GC estamos recebendo muitas requisições para `/api/box/init/undefined` e `/api/box/history/undefined`, esse tipo de request das linhas 44 e 45 https://github.com/gamersclub-booster/gamersclub-booster/blob/83dedff5b0404311afc8bcd5eea0a851dad37600/src/content-scripts/main/barraLevel.js#L44 precisam validar a existência da variável no `window`. Pra mim o ideal seria validar em que paths a adição de elementos na página via extensão deveriam funcionar, temos páginas internas e públicas para usuários deslogados que não faz sentido a extensão ser executada.

**Comment by DanillodeSouza** [comment]
@henriquelbsouza para as modificações terem efeito as pessoas precisam reinstalar a extensão, certo?
Se sim, consegue enviar uma mensagem no Discord de vocês? Tentei achar o link do server mas não achei.

**Comment by henriquelbsouza** [comment]
Feito, a v2.41.4 foi enviado pra webstore do chrome/firefox. Assim que aprovarem, basta reiniciar o navegador :)
