### ISSUE TITLE
Icones da lobby esta com quebra de linha

### ISSUE THREAD

**Issue by crashzk** [gamersclub-booster/gamersclub-booster#331]
Recentemente os icones da lobby estão com quebra de linha, algo assim.
![image](https://github.com/gamersclub-booster/gamersclub-booster/assets/32937653/5ce06593-9fe6-4cd7-8f64-93055e633a67)

**Comment by crashzk** [comment]
Já dei zoom na página e nada de mudar os icones, ficam só assim.

**Comment by jorgebrunetto** [comment]
Resolvido na ultima versão!
