### ISSUE TITLE
Imagem divergente

### ISSUE THREAD

**Issue by Jhamersom** [gamersclub-booster/gamersclub-booster#332]
Já alterei umas 10x a imagem da GC porém a imagem que aparece na parte superior continua a mesma da primeira vez que utilizei.

**Comment by henriquelbsouza** [comment]
Não entendi, o que isso tem a ver com extensão?

**Comment by Jhamersom** [comment]
Eu consigo anexar uma imagem aqui no chat pra facilitar a comunicação ?

**Comment by henriquelbsouza** [comment]
Sim, printa e ctrl+v. Mas não somos suporte da Gamersclub.

**Comment by Jhamersom** [comment]
![image](https://github.com/gamersclub-booster/gamersclub-booster/assets/135142382/c5c6d1dc-8fe5-4d12-a782-3ff2456fddb9)

**Comment by Jhamersom** [comment]
Então, vocês são do suporte da extensão certo ? oque estou me referindo é a extensão mesmo, aquela parte que circulei no top da pagina é exibida graças a extensão, eu quis dizer que a imagem que aparece ali em cima por mais que eu altere a imagem NA gamersclub  continua sempre a mesma imagem no topo da pagina.

**Comment by henriquelbsouza** [comment]
É cache provavelmente, ou a GC parou de suportar imagens do tamanho "medium"
https://static.gamersclub.com.br/players/avatar/17110/17110_full.jpg
https://static.gamersclub.com.br/players/avatar/17110/17110_medium.jpg

A que é utilizada lá em cima é medium, no card é full.

Tem como tentar dar alguns CTRL+F5 e alguns CTRL+R pra reiniciar o cache e ver se atualiza?

**Comment by Jhamersom** [comment]
Tentei aqui 4x CTRL + F5, e 2x CTRL +R, chegou inclusive a atualizar a imagem que troquei recentemente MAS aquela lá de cima não mudou hehe

**Comment by Jhamersom** [comment]
![image](https://github.com/gamersclub-booster/gamersclub-booster/assets/135142382/dd545052-6da4-4726-b60f-16bed6f3dd66)

**Comment by Jhamersom** [comment]
Show de bola Henrique, estou aqui aguardando, eu nem sabia que era tão simples o contato com o suporte assim, parabéns ai pelo suporte =)

**Comment by jorgebrunetto** [comment]
@Jhamersom poderia fazer um testes?
Desinstalar a extensão e atualizar a pagina.
Reinstalar a extensão.

**Comment by Jhamersom** [comment]
Posso sim, mas já fiz isso umas 4x.
________________________________
De: Jorge Brunetto ***@***.***>
Enviado: sexta-feira, 9 de junho de 2023 09:13
Para: gamersclub-booster/gamersclub-booster ***@***.***>
Cc: Jhamersom ***@***.***>; Mention ***@***.***>
Assunto: Re: [gamersclub-booster/gamersclub-booster] Imagem divergente (Issue #332)


@Jhamersom<https://github.com/Jhamersom> poderia fazer um testes?
Desinstalar a extensão e atualizar a pagina.
Reinstalar a extensão.

**Comment by jorgebrunetto** [comment]
É que atualizamos a extensão ontem, e tambem tem a opção de tirar a barra tambem podemos testar.

**Comment by jorgebrunetto** [comment]
![image](https://github.com/gamersclub-booster/gamersclub-booster/assets/5823077/23b982ec-f6da-4736-8da4-66be1965ade2)
Se mesmo assim não for tenta desativar essa opção

**Comment by jorgebrunetto** [comment]
E a ultima coisa que podemos testar é....
Abrir a extensão
Botão direito
Inspecionar elemento
Aplicação ou Application
Armazenamento ou Storange
Limpar dados ou Clear site data

![image](https://github.com/gamersclub-booster/gamersclub-booster/assets/5823077/155ba25c-e9a3-4878-acd7-6fcf0beb1522)

**Comment by Jhamersom** [comment]
Vou testar agora então.
________________________________
De: Jorge Brunetto ***@***.***>
Enviado: sexta-feira, 9 de junho de 2023 10:49
Para: gamersclub-booster/gamersclub-booster ***@***.***>
Cc: Jhamersom ***@***.***>; Mention ***@***.***>
Assunto: Re: [gamersclub-booster/gamersclub-booster] Imagem divergente (Issue #332)


E a ultima coisa que podemos testar é....
Abrir a extensão
Botão direito
Inspecionar elemento
Aplicação ou Application
Armazenamento ou Storange
Limpar dados ou Clear site data

[image]<https://user-images.githubusercontent.com/5823077/244710650-155ba25c-e9a3-4878-acd7-6fcf0beb1522.png>

**Comment by Jhamersom** [comment]
Acredito que essa imagem ai só esta servindo para bugar mesmo e dar dor de cabeça para os DEV, se vocês retirarem a imagem ficaria bom já, uma outra observação para ficar PERFEITO sem essa imagem seria descer um pouco essa barra e colocar no local onde não tem nada no site da GC, vou te mandar um print pra entender, fiz no paint mesmo coloquei o retângulo onde ficaria muito bom se fosse movido para lá, e se retirarem a foto vai dar certinho o tamanho.

**Comment by jorgebrunetto** [comment]
Na realidade temos um feat que irá subir para colocar a barra onde quiser arrastando, vai ficar bem bacana, fez o processo de dar um Clear Data?

**Comment by jorgebrunetto** [comment]
Tentamos uma correção aqui:

https://github.com/gamersclub-booster/gamersclub-booster/pull/336/commits/c39ebee2225ff85389e8dc5ccb3d1fc3866a18f9

**Comment by Jhamersom** [comment]
Precisa que eu teste aqui ?
