### ISSUE TITLE
Atualizar Manifest v2 pra v3

### ISSUE THREAD

**Issue by henriquelbsouza** [gamersclub-booster/gamersclub-booster#363]
![image](https://github.com/gamersclub-booster/gamersclub-booster/assets/1070818/518752f5-9d83-4106-bcd8-3e3c8c959267)

Tem que ver se funciona no moz firefox...

**Comment by jvdavim** [comment]
Se alguém estiver com tempo e paciência, aqui tem a documentação da Mozilla explicando o arquivo manifesto V3 para o Firefox:
https://extensionworkshop.com/documentation/develop/manifest-v3-migration-guide/

**Comment by henriquelbsouza** [comment]
Done.
