### ISSUE TITLE
BUG: Player Stats com max height bugado

### ISSUE THREAD

**Issue by pablo-padua** [gamersclub-booster/gamersclub-booster#367]
Ao abrir o lobby, o max height do player stats está provavelmente com height 100%, ao limitar (ex: 60px) fica normal

Before
![image](https://github.com/gamersclub-booster/gamersclub-booster/assets/46659839/f33931fa-ea6f-4fa9-ab28-68b9b8112f4c)

After
![image](https://github.com/gamersclub-booster/gamersclub-booster/assets/46659839/fe4a1f01-7468-4be3-b42c-40cbb1ac7b2e)

**Comment by henriquelbsouza** [comment]
é que ele deveria estar colado em baixo...

**Comment by henriquelbsouza** [comment]
e aqui ta funcionando, consegue colar ele embaixo e me passar as alterações? eu n consegui simular isso aqui...

**Comment by henriquelbsouza** [comment]
@pablo-padua A gente não conseguiu testar, mas o @jvdavim achou um bug e tentou corrigir no PR #368 

Quando liberar a versão 2.46.17 vc pode testar ai?

Já enviei pras lojas, se tiver corrigido pode fechar a issue :)
