### ISSUE TITLE
forçar criação de lobby

### ISSUE THREAD

**Issue by totinato** [gamersclub-booster/gamersclub-booster#37]
o botão forçar criação de lobby não funciona devido a uma overlay presente dentro de uma div com classe animsition e também uma outra div com a id lobby-create-denied-wrapper após as duas serem apagadas a criação da lobby fica facilmente disponível

**Comment by henriquelbsouza** [comment]
Boa tarde, pode explicar melhor? 
- Aqui logo que eu clico já muda pra "Forçando criação da lobby" com o botão pra cancelar.
- A funcionalidade é:
   - Se premium, tenta criar quando tem menos de 400
   - Se free, menos de 50 (esse número foi o único consistente que consegui encontrar, pode estar errado...)

Pode me informar navegador, etc...?

**Comment by totinato** [comment]
não sei como funciona para premium na gc mas quando é tentado a criação da lobby sendo free aparece uma janela na frente para  adquirir o premium e uma overlay que impede de criar a lobby mesmo que apareça após algumas tentativas essa janela que aparece ela não e fechada clicando no x de forma alguma, a única solução que consegui fazer pra utilizar a função de criação de lobby foi deletar no html do site tanto a overlay e essa janela o exemplo e essa imagem anexada
![9035812 314999988_image](https://user-images.githubusercontent.com/56313687/112183045-a14a5000-8bdc-11eb-89a4-e288b02aef62.png)

**Comment by totinato** [comment]
e também (não sei se era o esperado) ela não finaliza a criação da lobby

**Comment by henriquelbsouza** [comment]
Valeu! Essa tela é nova, vou ajustar =)

**Comment by henriquelbsouza** [comment]
Removi o botão por enquanto, tenho que conseguir uma conta sem premium pra fazer os testes até funcionar. Se tiver interesse em contribuir com um Pull Request, é muito bem vindo :)

**Comment by henriquelbsouza** [comment]
Corrigido no PR #46
