### ISSUE TITLE
Como ativar o Ready automático e como copiar o IP automaticamente?

### ISSUE THREAD

**Issue by mayconvs** [gamersclub-booster/gamersclub-booster#424]
Na [página de add-ons do Firefox](https://addons.mozilla.org/pt-BR/firefox/addon/gamersclub-booster/) diz que essa extensão possui Ready Automático e que Copia IP Automático, porém, o **Ready Automático** não está funcionando, por acaso ele dá apenas no último segundo do contador ou deveria ser instantâneo? De qualquer forma, há uma maneira de ativar? Pois o meu não parece estar funcionando...

Obrigado pela atenção e parabéns pelo ótimo trabalho que vocês fizeram nesta extensão.

**Comment by henriquelbsouza** [comment]
Boa tarde, a cópia de IP por enquanto não está funcionando mais, foi alterado na GC e não foi atualizado na extensão.

Sobre o auto ready, ainda funciona normalmente no chrome, faz tempo que não testo no firefox. Vou tentar tirar um tempinho essa semana pra ver isso.

**Comment by henriquelbsouza** [comment]
Você ativou nas opções?
![image](https://github.com/user-attachments/assets/537ffe23-e674-4650-ad4a-c624e4fa5f46)

**Comment by mayconvs** [comment]
Não tinha ativado... Logo após a minha pergunta que fui ver que tinha todas essas opções da extensão ai... Ativei e hoje a noite testarei, muito obrigado! ^^ Esse "Aceitar Termos da Ranked" é necessário pro Ready automático também?

**Comment by henriquelbsouza** [comment]
Não é necessário, só se for jogar o GC Solo, ai ele aceita os termos do GC Solo ali...

Se puder dar um feedback e fechar a issue caso funcione eu agradeço, vlw

**Comment by mayconvs** [comment]
Beleza, irei fechar. Muito obrigado pelo auxílio!

**Comment by mayconvs** [comment]
Beleza, irei fechar. Muito obrigado pelo auxílio!
