### ISSUE TITLE
AutoComplete

### ISSUE THREAD

**Issue by feejunior** [gamersclub-booster/gamersclub-booster#451]
Quando você seta 'Ocultar notificações de complete' ele funciona até certa hora, depois já começa a aparecer novamente o POP-UP. Mesmo com a opção setada ainda.

**Comment by henriquelbsouza** [comment]
Vou verificar, acho que pra limitar o som pelo menos, você pode fazer pela própria GC, vê se te ajuda enquanto isso :)

https://gamersclub.com.br/settings#notifications

**Comment by henriquelbsouza** [comment]
Valeu =)
