### ISSUE TITLE
Sugestão de melhoria, filtragem de lobby

### ISSUE THREAD

**Issue by victorhugoof** [gamersclub-booster/gamersclub-booster#51]
Adicionar recurso para filtrar lobby pelo nome;
Quando queremos jogar contra um amigo e tem muitas lobbys abertas fica muito complicado de procurar/acompanhar a lobby

**Comment by ozkcs** [comment]
Boa sugestão victor, iremos adicionar ao TO-DO.

**Comment by KINZs** [comment]
Eu fiz aqui pra mim, mas como é a criação dos lobbys é dinâmica, sempre aparece outros na filtragem, e não consigo fixar no primeiro lobby, sempre fica onde o titulo foi encontrado

![image](https://user-images.githubusercontent.com/48375198/115767878-f87c4580-a37f-11eb-9382-de46335f8dde.png)

**Comment by ttibau** [comment]
Pessoal, 

GC.Tibau aqui. 

Estamos trabalhando nisso e esta semana esta feature estará disponível nativamente na plataforma. 

Obrigado pela sugestão.

**Comment by henriquelbsouza** [comment]
> Pessoal,
> 
> GC.Tibau aqui.
> 
> Estamos trabalhando nisso e esta semana esta feature estará disponível nativamente na plataforma.
> 
> Obrigado pela sugestão.

Caraca, que da hora, vlw @ttibau :D 

Obrigado pelo heads up.

**Comment by henriquelbsouza** [comment]
https://twitter.com/GamersClubCS/status/1438515857584394245

Resolvido :P
