### ISSUE TITLE
Sugestão de melhoria: CI/CD para entrega contínua na Chrome Store

### ISSUE THREAD

**Issue by feliperugai** [gamersclub-booster/gamersclub-booster#52]
Fala galera, tudo certo?

Descobri a extensão esses dias e achei fantástica. Vim dar uma olhada no código e vi que existem algumas features (integração com Discord por exemplo) que estão no Github, mas não estão na loja de extensão do Chrome.

Fica a sugestão de criar um CI/CD para fazer a publicação automática na loja.

Dando uma pesquisada, achei essa Github Action:
[https://github.com/marketplace/actions/chrome-extension-upload-publish](https://github.com/marketplace/actions/chrome-extension-upload-publish)

Caso achem que faça sentido, me disponho à ajudar.

Abraços

**Comment by henriquelbsouza** [comment]
Salve @feliperugai blz? 

Então, eu usei essa extensão e fiz ela enviar direto pra loja, porém:
1- Só envia pro chrome, então o trabalho de enviar para o firefox ainda é manual (e pode acabar "esquecendo", já que tem que gerar o pacote manualmente pra isso)
2- a gente não está utilizando package.json pra mais nada e no fim estava enviando o node_modules inteiro fazendo com que a extensão passasse de menos de 70kb pra 700kb... 

Achei estranho e fiquei preocupado com a segurança e como não tenho exata certeza do que estava nesse pacote, preferi remover até achar uma outra solução. Já pensei em algumas soluções mas ainda não tive tempo de implementar.

Sobre a função do discord, ela foi finalizada recentemente pelo @ozkcs e ainda está em teste e por isso ainda não foi colocada nas lojas, inclusive se quiser testar a gente agradece :P

Temos que criar um conteúdo pra liberar essa função junto com a de som, talvez um vídeo, explicando como configurar etc... Mas a ideia é ser liberada em breve.

Obrigado pelo interesse e se quiser abrir PR/testar/dar feedback ficaríamos muito agradecidos pela contribuição :P 

Abraços! E entra no nosso discord: https://discord.com/invite/umx6bbuawh que é melhor pra trocar ideia =)

**Comment by feliperugai** [comment]
Tranquilo e por aí?

Entendi! Hoje não vou conseguir entrar no Discord, mas vou dar uma olhada na action e ver se consigo alguma solução pra subir pras outras lojas também.

Só uma pergunta, pq tomaram a a decisão e não usar um ```package.json```?

De qualquer jeito, gostei muito da ideia e vou clonar aqui pra ver se consigo ajudar em algo!

**Comment by henriquelbsouza** [comment]
Então, inicialmente era pra ser uma extensão que da ready basicamente hehe
No inicio eu fiz os scripts e colava tudo no console, depois migrei pra extensão com o intuito de facilitar minha vida, quando bateu 1k users eu comecei a dar uma atenção maior, mas como o tempo é limitado e os testes são difíceis de fazer (principalmente quando precisa jogar um jogo pra poder testar), acaba que evolui tudo muito lentamente e nunca tem tempo. Como é/era pouco código, usa apenas o jquery/axios, eu quis evitar complexidade. 

Hoje da pra refatorar a coisa toda e fazer diferente, mas como eu disse, tempo e dificuldade de testar meio que atrapalham...

No refactor o mais simples seria jogar todo o código pra dentro de um ./src e deixar as configs novas como package.json na raiz. (ai empacotava só o src)

Minha ideia no futuro era usar webpack e separar cada feature em um arquivo e depois só juntar tudo com webpack.

**Comment by henriquelbsouza** [comment]
Outra coisa, essa é a primeira extensão que eu escrevo na vida, nunca tinha feito nem um hello world, então se tiver conhecimento e tempo pra contribuir ou nos ajudar, só chamar :D

**Comment by feliperugai** [comment]
Hahahaha cara não tinha pardo pra pensar que realmente tem features que para testar vc tem que jogar a partida inteira kkkkkk

Eu cheguei a escrever uma extensão no passado que fazia algo parecido mas para outro site, e também foi a única que escrevi.

Hoje estou só com o celular, mas assim que tiver um tempo vou olhar e ver como consigo contribuir com o refactor.


Abraços e parabéns pela iniciativa (não aguentava mais perder os pré-ready porque estava no banheiro kkkkkkkkk)

**Comment by henriquelbsouza** [comment]
Valeu, sem stress, a gente faz quando da tempo né hehe

Se quiser trocar ideia/parear/etc... podemos marcar um horário, o @jvdavim o @ozkcs também contribuem bastante...

**Comment by henriquelbsouza** [comment]
Implementado no #61
