### ISSUE TITLE
Opção para aceitar automaticamente convites para complete

### ISSUE THREAD

**Issue by wadami** [gamersclub-booster/gamersclub-booster#54]
Primeiro de tudo, parabéns pelo trabalho! A extensão é muito útil.
Queria deixar minha sugestão para adicionar uma funcionalidade para aceitar automaticamente convite de complete. 
Talvez um ponto de atenção seria da opção ser habilitada por partida/aceite de convite, ou seja, quando o aceite for realizado automaticamente a opção é desabilitada até que o usuário a habilite novamente. Acho que isso pode evitar que o aceite ocorra quando o jogador já estiver numa partida.

**Comment by jvdavim** [comment]
Tá aí uma funcionalidade legal. Acho que o único problema é que pode acabar criando uma desvantagem para outros players que querem também entrar de complete e não tem a extensão, ou têm a extensão, mas um pc mais fraco. 

Uma possível abordagem seria escolher um aleatório de delay entre 1 e 5 segundos, por exemplo, depois que o botão de complete aparecer para dar chance à todos de aceitar e ainda assim manter a funcionalidade. O q vc acha @henriquelbsouza ?

@wadami, obrigado pela sugestão!

**Comment by ricardobr001** [comment]
Salve pessoal, miley da GC aqui
Acho que seria interessante ter esse delay aleatório de 1 a 5 segundos para aceitar o pedido de complete
Pois jogadores que não possuirem a extensão realmente teram uma desvantagem :slightly_frowning_face: 
Acham que é uma alteração simples de ser feita?

**Comment by jvdavim** [comment]
Opa, @ricardobr001. Eu implementei essa parte. Sim, cara. Com certeza podemos colocar um delay aleatório de 1 a 5 segundos. Vou estar implementand hoje mesmo e vou pedir para o @henriquelbsouza lançar o patch na loja o mais breve possível para não prejudicar a nossa comunidade. Obrigado pela atenção aí!

**Comment by pzGC** [comment]
Clan, recebemos um report na GC referente a essa funcionalidade. O jogador já estava em uma lobby com amigos, e aceitou o pedido de complete automaticamente, e reportou como um bug da plataforma. Seria importante fazer um check para validar se o jogador já esta em uma lobby ou fila da ranked antes de aceitar efetivamente o pedido de complete.

**Comment by jvdavim** [comment]
Opa, @pzGC. Obrigado pelo feedback. Hoje a noite vou dar uma olhada nisso também. Acabou que esse patch saiu pouco depois da plataforma mudar, então o botão ficou bugado. Já estou trabalhando para corrigir, e vou adicionar essa verificação.
