### ISSUE TITLE
Bug voz Gaules

### ISSUE THREAD

**Issue by ighauu** [gamersclub-booster/gamersclub-booster#57]
Se vc sair e entrar na página da partida já iniciada, o áudio é reproduzido novamente, não sei se é bug só do áudio do Gaules, ou em todos os áudios

**Comment by ozkcs** [comment]
Então como essa feature funciona observando quando há algum botão de ready disponível, sempre que abrir a pagina e tiver um, ele vai disparar o audio. Estamos trabalhando para descobrir outro jeito de fazer o som sair sem duplicar, ou quando acionar outro botão. Obrigado pelo feedback @ighauu

**Comment by henriquelbsouza** [comment]
Estamos cientes, essa ainda é uma funcionalidade experimental, assim que resolver isso acho que ta pronta :)

Obrigado pelo report.

**Comment by henriquelbsouza** [comment]
Corrigido no PR #60 

Vai ser lançado na próxima versão
