### ISSUE TITLE
Lista negra

### ISSUE THREAD

**Issue by gironni** [gamersclub-booster/gamersclub-booster#78]
Seria interessante incluir um feat de adicionar perfil de pessoas que nao queremos jogar ou contra ou no nosso time. As vezes ele é tóxico ou suspeitamos que use cheats, poderiamos adicionar ele na lista e aparecer um "popup", ou uma msg dizendo que alguem da lista negra esta na lobby

**Comment by jvdavim** [comment]
Implementado no PR #84

**Comment by henriquelbsouza** [comment]
Chamamos de block list (Lista de Bloqueio) e está disponível no release 2.5.0.
