### ISSUE TITLE
Opções Lobby não estão funcionando

### ISSUE THREAD

**Issue by baroca** [gamersclub-booster/gamersclub-booster#88]
As opções da aba Lobby parecem não estar funcionando. Ao abrir uma lobby, não vem selecionado "Privada" ou qualquer mapa de pré veto.

![image](https://user-images.githubusercontent.com/2146876/125325728-a7914300-e317-11eb-8090-5b08c966b14b.png)
![image](https://user-images.githubusercontent.com/2146876/125325479-5c773000-e317-11eb-92d9-6089d7a2b5f2.png)

**Comment by henriquelbsouza** [comment]
Boa tarde, essas funções servem apenas pro "Forçar criação da lobby" atualmente.

![image](https://user-images.githubusercontent.com/1070818/125326014-f8a13700-e317-11eb-9926-25a4d7423d15.png)


Se criar por ali, cria com as predefinições :)

**Comment by baroca** [comment]
Então, sempre tive a impressão que esse botão teria de ser ativado, o que aqui só mudar o botão para esse estado:

![image](https://user-images.githubusercontent.com/2146876/125326748-be846500-e318-11eb-9c20-c3031a2afbdf.png)

E depois teria que clicar no botão normal de criar lobby.
O "forçar criação" deveria abrir direto a janela de pré vetos? Porque aqui não abre.
Estou no Firefox, testarei no chrome também.

**Comment by henriquelbsouza** [comment]
Ele deveria criar a lobby rápidamente, se você estiver com o CS:GO + Anti-cheat aberto.

**Comment by henriquelbsouza** [comment]
https://user-images.githubusercontent.com/1070818/125327477-892c4700-e319-11eb-8f80-471a73d2252c.mp4

@baroca aqui ta funcionando, você sabe olhar o console e ver se tem algum erro?

**Comment by baroca** [comment]
Testei aqui e no Chrome funciona como você explicou.
No Firefox, não abre. No console recebo `SyntaxError: The URI is malformed.` no arquivo `lobby.js`

Testei somente na versão em produção da store, onde o js vem truncado, então fica difícil o debug exato.
Caso ninguém solucione eu instalarei do source.

**Comment by henriquelbsouza** [comment]
Beleza, valeu, vou instalar o FF e tentar entender o que pode estar rolando.

Valeu pelo report :)

**Comment by baroca** [comment]
Não sei se já avançaram além disso, mas parece que o problema está na URL relativa na requisição post do axios no Firefox.
Com URL relativa, o erro:

![image](https://user-images.githubusercontent.com/2146876/125816951-784318ab-8c29-47dc-953d-0fec0a43a590.png)

Já utilizando URL absoluta:

![image](https://user-images.githubusercontent.com/2146876/125817069-928235da-29ac-4cb3-b12b-d2ed95878c14.png)

**Comment by henriquelbsouza** [comment]
Então, eu percebi isso também, até fiz uns testes aqui que aparentemente funciona, mas ainda falta teste e tempo pra fazer o deploy...

Da pra usar o GC_URL que ta na lib/constants.js

**Comment by henriquelbsouza** [comment]
@baroca eu fiz o PR ali com o fix, porém meu firefox não "guarda" a info quando eu carrego a extensão no modo dev... Não queria mandar pra loja antes de testar isso, você tem algum conhecimento pra fazer esse teste?

No meu caso o chrome.storage.sync ta voltando sempre null, apesar de funcionar normalmente no opera/chrome :/

**Comment by baroca** [comment]
Você tem que setar um Addon ID para testar, do contrário a API de storage não funciona.
Tem que editar o manifest.json com uma chave extra.

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_specific_settings#

**Comment by henriquelbsouza** [comment]
> Você tem que setar um Addon ID para testar, do contrário a API de storage não funciona.
> Tem que editar o manifest.json com uma chave extra.
> 
> https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_specific_settings#

É, no fim consegui testar ontem, mas como não tava no PC, não tinha o anticheat/csgo, só vi que funcionou a request... Já vi que você comentou um outro bug ali... 

Vou ver se penso em alguma solução, provavelmente o firefox ta bloqueando a execução por segurança ou algo assim....

**Comment by henriquelbsouza** [comment]
@baroca to tentando resolver a criação da lobby, gc mudou o layout e deu uma cagada maior ainda kkk
ta com tempo hoje?

**Comment by henriquelbsouza** [comment]
Minha ideia é tentar isso: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Sharing_objects_with_page_scripts#accessing_page_script_objects_from_content_scripts

Mas não to conseguindo rodar no firefox...

**Comment by baroca** [comment]
Hoje ta meio corrido pra mim, mas devo conseguir no fim de semana. Se eu conseguir antes aviso.

**Comment by henriquelbsouza** [comment]
@baroca cara, acho que resolvemos =)

Se puder testar a branch development, ai na já coloco nas lojas essa correção.

**Comment by henriquelbsouza** [comment]
Enviei pras lojas, aparentemente está funcionando, pelo menos pra mim (consegui fazer um pouco dos testes no FF).

Agora funciona também os alertas da extensão no FF, que antes não funcionava :)
