### ISSUE TITLE
Opção de verificar partidas.

### ISSUE THREAD

**Issue by RenatoJaudy** [gamersclub-booster/gamersclub-booster#94]
Adicionar a opção de verificar as partidas, igual na extensão "GamersClub Enchancer" .
Consiste em o usuário que habilitar essa função possar ver, se algum intregante de alguma partida foi banido.

**Comment by henriquelbsouza** [comment]
![image](https://user-images.githubusercontent.com/1070818/130070171-459162c5-ffc6-4e1f-b889-47dbf1397d1c.png)
Não seria essa imagem com um V verde? Se tiver usuário banido vai aparecer com um X vermelho:

![image](https://user-images.githubusercontent.com/1070818/130070284-181c18c5-68fd-4614-a391-e0be93d3503a.png)

**Comment by RenatoJaudy** [comment]
Sim, seria. Mas no meu caso não esta aparecendo.

**Comment by henriquelbsouza** [comment]
Pode me passar a URL? Atualmente só tem funcionado em /minhas-partidas

Vou tentar encontrar todas as urls e corrigir, obrigado pelo report. 

A propósito, essa feature é o motivo dessa extensão existir, foi a primeira coisa que foi criada :P

**Comment by thiagoac33** [comment]
Olá, Henrique! Também não estava aparecendo para mim e funcionou quando eu abri com a url:
https://gamersclub.com.br/minhas-partidas.

Atualmente quando clica em minhas partidas vai para esta url:
https://gamersclub.com.br/my-matches

**Comment by thiagoac33** [comment]
Aproveitando a issue. Quando vai em /minhas-partidas e quantidade de partidas não é suficiente para ter paginação (ou seja, uma outra página) não aparece também as verificações das partidas.

ex:
![image](https://user-images.githubusercontent.com/30728909/130125516-87f1497e-398d-4b0c-b985-954b716cf3fe.png)

**Comment by henriquelbsouza** [comment]
Corrigido na ultima versão :D
