### ISSUE TITLE
Funcionalidades

### ISSUE THREAD

**Issue by zenak7** [gamersclub-booster/gamersclub-booster#97]
As funcionalidades de "Verificar em cada partida se tem jogador banido", "Adiciona um background com cores para vitória/derrota e empate" e "Copiar IP Automático
" não estão funcionando mais ?

**Comment by henriquelbsouza** [comment]
Já foi corrigido os dois primeiros, o ultimo ainda não tive chance de fazer no novo layout.

**Comment by henriquelbsouza** [comment]
Corrigido e enviado pras lojas na última versão :)
