### ISSUE TITLE
Lista de bloqueio

### ISSUE THREAD

**Issue by vttrz** [gamersclub-booster/gamersclub-booster#98]
Funcionalidade não está funcionando corretamente. Quando é feito o clique, expande os detalhes sobre o jogador. Dei uma olhada nas outras issues e não vi nenhuma do tipo.

![image](https://user-images.githubusercontent.com/34952739/133893153-b8cb9b6d-4324-460d-9ba6-1c8617f7901c.png)

**Comment by henriquelbsouza** [comment]
Pode compartilhar o navegador que está utilizando?

**Comment by victorhrqs** [comment]
Firefox

**Comment by fedebabrauskas** [comment]
This happens because the whole `<tr>` element is clickable.
![image](https://user-images.githubusercontent.com/19313864/134271922-a7e40d11-03d0-4eee-bc1d-adf064c9f181.png)

We could remove the listener from that element, and assign it to the plus button.
![image](https://user-images.githubusercontent.com/19313864/134272331-7ff941d6-ecb7-4297-b6a3-496348204bd3.png)

**Comment by victorhrqs** [comment]
Nice! It's better

**Comment by henriquelbsouza** [comment]
Estou dando uma olhada nessa feature e não está funcionando como deveria. Vou tentar corrigir nas próximas semanas.

**Comment by victorhrqs** [comment]
Sim, fiz algumas modificações no projeto para realizar alguns testes. Aumentando o z-index no css funciona, porém quando clicamos no texto "ADICIONAR A LISTA DE BLOQUEIO", toda a tr é expandida. O ideal seria fazer como @fedebabrauskas recomendou.

**Comment by joelemanoel** [comment]
> Sim, fiz algumas modificações no projeto para realizar alguns testes. Aumentando o z-index no css funciona, porém quando clicamos no texto "ADICIONAR A LISTA DE BLOQUEIO", toda a tr é expandida. O ideal seria fazer como @fedebabrauskas recomendou.

Talvez rodar o js para fechar não seria uma solução?

**Comment by henriquelbsouza** [comment]
Não acho que tenha uma solução simples, vou tentar tirar umas horas pra isso esse mês.

**Comment by henriquelbsouza** [comment]
Salve @ronaldofsn, antigamente listava corretamente, provavelmente introduzimos esse bug em algum momento. Assim que tiver um tempo vou dar uma olhada nisso, obrigado pelo report!

**Comment by jorgebrunetto** [comment]
Subindo uma nova versão com correção

**Comment by henriquelbsouza** [comment]
Mandei pras lojas, quem teve problemas se puder testar eu agradeço!

Obrigado ao @jorgebrunetto por ter feito as alterações e corrigido a feature :)

Inclusive agora, se o cara ta na lista de bloqueio ele fica vermelho na lobby que você criou e nas lobbies pra desafiar :)

**Comment by guilhermeyo** [comment]
@henriquelbsouza o link pra mim nem aparece, testei no chrome e firefox.

Quando deixei aberto por um tempo enquanto eu procurava o repo pra abrir issue apareceu, porem o botão não clicava, ficava expandindo as infos do jogador. :/

**Comment by jorgebrunetto** [comment]
Corrigida pela 10x, eles mudam alguns parametros e quebra a lista toda, dessa vez mudaram de jogador para player, e quebrou o salvar e quebrou a exibição, já foi corrigida na proxima.
