### ISSUE TITLE
Para a comunidade.

### ISSUE THREAD

**Issue by mandr9ke** [gamersclub-booster/gamersclub-booster#99]
botar a cache antiga na rotação de mapa das lobby/ranked's, igual fizeram com a cobble. seria tipo um saudades cache

**Comment by cervieriiess** [comment]
EU ACHARIA MUITA LEGAL EU AMAVA A CACHE ANTIGA E JA VI MILHARES DE PESSOAS PEDINDO SERIA UMA BOA

**Comment by lokinho1** [comment]
Nossa... ia ser muito nostálgico ! Muito bom.

**Comment by henriquelbsouza** [comment]
Pessoal, não somos a gamersclub e sim uma extensão externa que não tem relação nenhuma com a plataforma, essas decisões não são tomadas por nós e nem temos como fazer isso =/
